runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*\.(gif|png|jpg))$
  static_files: www/\1
  expiration: "7d"
  upload: www/.*\.(gif|png|jpg)$

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)